name: flake8

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: flake8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "*"
      - name: flake8
        uses: py-actions/flake8@v2